version: "3.9"

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

#  kotlin:
#    build:
#      context: .
#      dockerfile: src/main/docker/Dockerfile.jvm
#    ports:
#      - "1313:8080"
